\documentclass[11pt]{article}
\usepackage{fancyvrb}
\begin{document}

<<>>=
xxx <- 1000
yyy <- 1000
@ 

\begin{enumerate}
\item sd
\item add
\end{enumerate}

\verb|kkkkkk| and \verb|llllll| og  \verb|sss|

<<>>=
library(patchwork)
library(ggplot2)
p1 <- ggplot(CO2, aes(x=conc, y=uptake, color=Treatment, group=Plant)) + geom_line() + geom_point() + facet_grid(~Type)
p1
@ 

\begin{enumerate}
\item sad sad
  asd
  asd
  
\item asdda
\end{enumerate}

\end{document}
